/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useEffect, useRef, type JSX } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import type { GLTF } from 'three/examples/jsm/Addons.js';
import { useControls } from 'leva';

type GLTFResult = GLTF & {
	nodes: {
		Sphere026: THREE.SkinnedMesh;
		Sphere026_1: THREE.SkinnedMesh;
		Sphere026_2: THREE.SkinnedMesh;
		Sphere026_3: THREE.SkinnedMesh;
		Sphere026_4: THREE.SkinnedMesh;
		Sphere026_5: THREE.SkinnedMesh;
		Root: THREE.Bone;
	};
	materials: {
		Fish_Main: THREE.MeshStandardMaterial;
		Fish_Secondary: THREE.MeshStandardMaterial;
		Eye_Black: THREE.MeshStandardMaterial;
		Eye_White: THREE.MeshStandardMaterial;
		Mouth: THREE.MeshStandardMaterial;
		Fish_Flaps: THREE.MeshStandardMaterial;
	};
};

type ActionName =
	| 'Death'
	| 'Duck'
	| 'HitReact'
	| 'Idle'
	| 'Jump'
	| 'Jump_Idle'
	| 'Jump_Land'
	| 'No'
	| 'Punch'
	| 'Run'
	| 'Walk'
	| 'Wave'
	| 'Weapon'
	| 'Yes';

export function Fish(props: JSX.IntrinsicElements['group']) {
	const group = useRef<THREE.Group>(null);
	const { nodes, materials, animations } = useGLTF(
		'/models/Fish.gltf',
	) as unknown as GLTFResult;

	const { actions } = useAnimations(animations, group);

	const { animation } = useControls({
		animation: {
			value: 'Idle',
			options: Object.keys(actions),
		},
	});

	useEffect(() => {
		actions[animation]?.reset().fadeIn(0.5).play();

		return () => {
			actions[animation]?.fadeOut(0.5);
		};
	}, [animation]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="CharacterArmature">
					<group name="Fish">
						<skinnedMesh
							name="Sphere026"
							geometry={nodes.Sphere026.geometry}
							material={materials.Fish_Main}
							skeleton={nodes.Sphere026.skeleton}
						/>
						<skinnedMesh
							name="Sphere026_1"
							geometry={nodes.Sphere026_1.geometry}
							material={materials.Fish_Secondary}
							skeleton={nodes.Sphere026_1.skeleton}
						/>
						<skinnedMesh
							name="Sphere026_2"
							geometry={nodes.Sphere026_2.geometry}
							material={materials.Eye_Black}
							skeleton={nodes.Sphere026_2.skeleton}
						/>
						<skinnedMesh
							name="Sphere026_3"
							geometry={nodes.Sphere026_3.geometry}
							material={materials.Eye_White}
							skeleton={nodes.Sphere026_3.skeleton}
						/>
						<skinnedMesh
							name="Sphere026_4"
							geometry={nodes.Sphere026_4.geometry}
							material={materials.Mouth}
							skeleton={nodes.Sphere026_4.skeleton}
						/>
						<skinnedMesh
							name="Sphere026_5"
							geometry={nodes.Sphere026_5.geometry}
							material={materials.Fish_Flaps}
							skeleton={nodes.Sphere026_5.skeleton}
						/>
					</group>
					<primitive object={nodes.Root} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/Fish.gltf');
